/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as ComparatifsIdRouteImport } from './routes/comparatifs.$id'
import { Route as FacturesIdRouteImport } from './routes/factures.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparatifsIdRoute = ComparatifsIdRouteImport.update({
  id: '/comparatifs/$id',
  path: '/comparatifs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesIdRoute = FacturesIdRouteImport.update({
  id: '/factures/$id',
  path: '/factures/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/reglages': typeof ReglagesRoute
  '/comparatifs/$id': typeof ComparatifsIdRoute
  '/factures/$id': typeof FacturesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/reglages': typeof ReglagesRoute
  '/comparatifs/$id': typeof ComparatifsIdRoute
  '/factures/$id': typeof FacturesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/reglages': typeof ReglagesRoute
  '/comparatifs/$id': typeof ComparatifsIdRoute
  '/factures/$id': typeof FacturesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/catalogue' | '/reglages' | '/comparatifs/$id' | '/factures/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogue' | '/reglages' | '/comparatifs/$id' | '/factures/$id'
  id:
    | '__root__'
    | '/'
    | '/catalogue'
    | '/reglages'
    | '/comparatifs/$id'
    | '/factures/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogueRoute: typeof CatalogueRoute
  ReglagesRoute: typeof ReglagesRoute
  ComparatifsIdRoute: typeof ComparatifsIdRoute
  FacturesIdRoute: typeof FacturesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparatifs/$id': {
      id: '/comparatifs/$id'
      path: '/comparatifs/$id'
      fullPath: '/comparatifs/$id'
      preLoaderRoute: typeof ComparatifsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures/$id': {
      id: '/factures/$id'
      path: '/factures/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof FacturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogueRoute: CatalogueRoute,
  ReglagesRoute: ReglagesRoute,
  ComparatifsIdRoute: ComparatifsIdRoute,
  FacturesIdRoute: FacturesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
